'use strict';
/**
 * Finto modulo `pg` basato su SQLite in memoria: serve a far girare l'intera suite
 * attraverso l'adapter Postgres (segnaposto $1..$n, transazioni su client, rowCount, RETURNING).
 * NON sostituisce un test su un vero Postgres: traduce solo le poche differenze di sintassi.
 */
const { DatabaseSync } = require('node:sqlite');

class Pool {
  constructor() {
    this.raw = new DatabaseSync(':memory:');
    this.raw.exec('PRAGMA foreign_keys = ON');
    this.queries = [];
  }
  on() {}
  async query(sql, params = []) {
    this.queries.push(sql);
    const s = sql
      .replace(/INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/g, 'INTEGER PRIMARY KEY AUTOINCREMENT')
      .replace(/\bBYTEA\b/g, 'BLOB')
      .replace(/\$(\d+)/g, '?$1');
    const multi = params.length === 0 && /;\s*\S/.test(s.trim().replace(/;\s*$/, ''));
    if (multi) {
      this.raw.exec(s);
      return { rows: [], rowCount: 0 };
    }
    const stmt = this.raw.prepare(s);
    const p = params.map((v) => (v === undefined ? null : v));
    if (stmt.columns().length > 0) {
      const rows = stmt.all(...p);
      return { rows, rowCount: rows.length };
    }
    const r = stmt.run(...p);
    return { rows: [], rowCount: Number(r.changes) };
  }
  async connect() {
    return { query: (s, p) => this.query(s, p), release() {} };
  }
  async end() {
    this.raw.close();
  }
}

module.exports = { Pool, types: { setTypeParser() {} } };
